//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace chat_signalr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chat
    {
        public int id { get; set; }
        public string name { get; set; }
        public string message { get; set; }
        public string img_url { get; set; }
        public Nullable<bool> active_stat { get; set; }
        public Nullable<System.DateTime> sent_time { get; set; }
        public string receiver { get; set; }
    
        public virtual user user { get; set; }
    }
}
